[tool.bumpversion]
current_version = "0.3.25-rc0"
commit = true
message = "chore: bump version: {current_version} → {new_version}"
commit_args = "--cleanup=verbatim"
tag = true
tag_name = "v{new_version}"
tag_message = "Version: {new_version}"

[[tool.bumpversion.files]]
filename = "Dockerfile"
search = "LABEL version={current_version}"
replace = "LABEL version={new_version}"
