name: Test Report
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: 0
    - name: Git Fetch
      run: git fetch --force --tags
    - name: Setup go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      with:
        go-version: stable
    - name: Run Unit Tests
      run: make unit-test
    - name: Test Report
      uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3
      if: success() || failure()
      with:
        name: Unit Test Results
        path: ./build/reports/**-test.xml
        reporter: java-junit
        fail-on-error: 'true'
    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: unit-test-reports
        path: ./build/reports/**
